#pragma once

// serial connection
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0
#define SELECT_SOFT_SERIAL_SPEED 1
#define SERIAL_USART_PIN_SWAP

// direct LED pins
#define LED_NUM_LOCK_PIN GP14
#define LED_CAPS_LOCK_PIN GP12
#define LED_SCROLL_LOCK_PIN GP15

// split keyboard
#define SPLIT_LED_STATE_ENABLE
#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_TIMEOUT 3000

// bootloader
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
